### ISSUE TITLE
[ Vote ] 여러개의 투표를 볼 수 있는 방법

### ISSUE THREAD

**Issue by henization** [TeamPiickle/client#125]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [x] Feature (제가 해냈습니다)

## 내용

- 현재는 투표를 한개씩 밖에 못보는데, 여러개를 한번에 볼 수 있는 방법 고안 
![image](https://user-images.githubusercontent.com/89568030/181184223-7c13e941-995b-4999-b0a4-2f77a73b26e9.png)

## 체크리스트

- [x] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[ {페이지명} - {세부명} ] 테스트 이슈명`
- [x] Assignees / Labels / Milestone 선택
- [x] VoteSlider 컴포넌트 생성
- [x] 투표 slider 기능
- [x] 다시 투표하기 버튼 bug
- [ ] 로그인 모달창 silder.tsx 위에 띄우기
- [ ] 투표 데이터 4개밖에 없음~~ 확인필여
- [ ] getgetget
- [ ] 메뉴바 -> 피클미

**Comment by joohaem** [comment]
페이지네이션으로 구현합니다
