### ISSUE TITLE
[ Login ] logout 실행 시, 작동 오류

### ISSUE THREAD

**Issue by NYeonK** [TeamPiickle/client#298]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [ ] Refactor (리모델링 재개발)
- [ ] Fix (내가 해결해주지)
- [x] Bug (삐용삐용 큰일 났어 / 질문)
- [ ] Feature (제가 해냈습니다)

## 내용

- 기존 로그인이 된 상태에서 로그아웃 버튼을 클릭하면, 실행이 안됩니다. (localStorage 토큰이 안사라짐)

## 체크리스트

- [ ] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[ {페이지명} - {세부명} ] 테스트 이슈명`
- [ ] Assignees / Labels / Milestone 선택
- [ ] ...todos, ...alert

**Comment by joohaem** [comment]
https://w1655692613-dsw141740.slack.com/archives/C04N6FV29RA/p1688190560359289?thread_ts=1688151858.992159&cid=C04N6FV29RA
